apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-frontend-ingress
spec:
  rules:
    - host: chat.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chat-frontend-service
                port:
                  number: 80
