apiVersion: v1
kind: Service
metadata:
  name: chat-frontend-service
spec:
  type: NodePort
  selector:
    app: chat-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080   # final URL = http://localhost:30080
apiVersion: v1
kind: Service
metadata:
  name: chat-frontend-service
spec:
  type: NodePort
  selector:
    app: chat-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
